ci:
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
        args: [--write] # edit files in-place
        additional_dependencies:
          - prettier
          - prettier-plugin-svelte
          - svelte

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.0.0-rc.0
    hooks:
      - id: eslint
        files: \.(js|svelte)$
        types: [file]
        args: [--fix]
        additional_dependencies:
          - eslint
          - svelte
          - eslint-plugin-svelte3

  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
      - id: markdownlint
        # MD013: Line length
        # MD029: Ordered list item prefix
        # MD033: Inline HTML
        args: [-r, '~MD013,~MD029,~MD033']

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        exclude: yarn.lock
